### ISSUE TITLE
Improved motor driver

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#3]
The motors that we will be using consume a little more power.  Use higher power, lower resistance FET drivers.  Design that will prevent the opportunity to turn on both series FET's at the same time.

**Comment by bus710** [comment]
< Update > 

So far I installed ARM-GCC on Ubuntu 16.04. it could be easier but there was too many confusing ways to do it so that it took pretty long time than my initial expectation. Essentially, we can just leverage a PPA from ARM (https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa) 

Now I am trying to do same way with Vedder's operation to run the motor I bought. (http://vedder.se/2015/01/vesc-open-source-esc/) After this, I will try to write my own code for STM32F0DISCOVERY, which will be a master controller for OpenESCs via CAN communication. 

When I reach to this point, I will re-design the boards (Discovery and OpenESC) to make it to fit our purpose. Of course, I may adjust the motor and controller's parameter to drive our system. To do so, we need to test with a frame. 

I very appreciate your patience.
