### ISSUE TITLE
research arduino code for v2 control

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#31]
Are there existing libraries for controlling motors with a joystick?

Document functional requirements for software and technical approach.

In future state arduino may communicate joystick commands to odroid to do high level control.

**Comment by dylanvaughn** [comment]
Oscar + Husein

**Comment by tnahcrem** [comment]
Hi Dylan,
Can you please grant me access to the project ?
Thanks,
husein

**Comment by dylanvaughn** [comment]
@tnahcrem done!

**Comment by tnahcrem** [comment]
This is a good/easy tutorial to get started with the joystick on arduino.
https://www.arduino.cc/en/Tutorial/JoyStick

Also attached zip contains  refrence document from a Joystick vendo(parallax)
[27800-2-Axis-Joystick-KickStart.zip](https://github.com/robomakery/pvc-powerchair/files/832232/27800-2-Axis-Joystick-KickStart.zip)

**Comment by miliapa** [comment]
https://www.engineersgarage.com/contribution/joystick-controlled-dc-motor

James comment: _Although the article uses the phrase "joystick" he is actually using a single pot to control a single motor. We need to use two pots in an actual joystick arrangement to coordinate the movement of two motors, in a way that is not direct. E.g. one pot doesn't control one motor. Instead, one pot controls both motors forward and back, and the other pot offsets the speed of the left or right motor to turn._

_Also, we wanted to keep to the Arduino to make it as easy and truly open source as possible. Unless someone has a programmer for an Atmel chip, or wants to document how to program it, I think we should stick with other sources._

**Comment by tnahcrem** [comment]
@miliapa  Thanks for sharing. It looks like I have to register to get access to source code ? If you have access can you share the code with us ?

**Comment by johanisforever** [comment]
A few days I spoke to Husein, and we agree that we need to start developing the program base on
the following code. We will use what we can.

https://www.arduino.cc/en/Tutorial/JoyStick

To code and test I built a prototype. I will be passing it to Husein once he comes back from his trip since I also will be going on a trip. We will be using Arduino. I will attach pics of the development platform, don't laugh it is just a development board.
Thing to keep in mind:
-I included a diagram of the current set up.
-I included a list of parts of the current set up and the required parts for the final set up.
- I include some pushbutton and light so we can code it in a way that when completed the PWM can be adjusted easy for different motors.  Different motor may need different PWM frequencies for optimum performance. Also, high RPM with low gear motors will need shorter duty cycles to prevent the motor from spinning too fast.
-currently I chose a  10 Amp h-bridge to power small motors, the final product will require a higher Amp h-bridge and higher wire gage.
- The 12Volt battery for the current set up may be too heavy, so I may have to change the battery.
-IMPORTAN!!!!! use the LEDs to first test both the PWM and the break signals before making the final connections to the H-bridge. Giving both commands, forward and back, at the same time will result in a short that will destroy the h-bridge. 
-To prevent any over-current damage a fuse of 8 amp will protect the entire circuit. 
- As far as PWM I would like to start with a 25% duty cycle, then see how fast the motosr rotate, if they are too slow we can increase the duty cycle until we determine the max allowable speed. Once we agree on the max allowable speed for a particular motor, we can divide the duty cycle by 5 increments. I say by 5 because I believe that 5 speeds would be enough for the wheel chair,
Example:If a reasonable fast speed is attained at 50% duty cycle. then 40%, 30%, 20%, 10% duty cycles will control the slower speeds, naturally 0% would mean the stop command. 
Now this idea may, or may not work, but once the code be completed, we can experimentally determine if those are good values for speed control.  
Different motors will require different max speeds, but we can write the code with options to set the max speed via push buttons. For safety we could put a requirement that to enable the push buttons the user would have to temporary jumper a particular input to a particular output and so entering the "setting mode". Once the jumper is removed, accidental pressing any button would not have any effect. 

I did not included the charging circuit yet, but any trickle charger will do.

Note to all, my schematic does not supersede the V1_5 Drawing.pdf submitted a week ago, rather it complements it. 
![schematic](https://cloud.githubusercontent.com/assets/18096333/24063792/5cbb5e9a-0b1e-11e7-852a-c89e7fb5d520.png)
[parts.docx](https://github.com/robomakery/pvc-powerchair/files/851821/parts.docx)

**Comment by johanisforever** [comment]
this are the images of the "development platform"
If I have time I will start coding Monday, if Husein or someone else want to try just let me know, 
I will speak to Dylan about coordinating the development. 
 
![1](https://cloud.githubusercontent.com/assets/18096333/24064008/6c0aaa94-0b1f-11e7-9b1c-8f980e1274e5.jpg)
![2](https://cloud.githubusercontent.com/assets/18096333/24064010/6c0d7e54-0b1f-11e7-80fa-848a6386662a.jpg)
![3](https://cloud.githubusercontent.com/assets/18096333/24064009/6c0d4600-0b1f-11e7-926b-8b9e7b825198.jpg)
![4](https://cloud.githubusercontent.com/assets/18096333/24064011/6c0f0c1a-0b1f-11e7-8f3f-9caf8b7cf586.jpg)
